version: '3.8'

services:
  # =============================================================================
  # Genesis AI Deep Agents Service
  # =============================================================================
  genesis-ai-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: genesis-ai-service
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Application
      APP_NAME: genesis-ai-service
      DEBUG: "false"
      LOG_LEVEL: INFO
      
      # Database
      DATABASE_URL: postgresql://genesis_ai_user:${POSTGRES_PASSWORD}@genesis-ai-db:5432/genesis_ai_db
      
      # Redis
      REDIS_URL: redis://genesis-ai-redis:6379/0
      
      # DigitalCloud360 Integration
      DIGITALCLOUD360_API_URL: ${DIGITALCLOUD360_API_URL}
      DIGITALCLOUD360_SERVICE_SECRET: ${DIGITALCLOUD360_SERVICE_SECRET}
      
      # AI APIs
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      TAVILY_API_KEY: ${TAVILY_API_KEY}
      LOGOAI_API_KEY: ${LOGOAI_API_KEY}
      
      # Security
      SECRET_KEY: ${SECRET_KEY}
    depends_on:
      - genesis-ai-db
      - genesis-ai-redis
    volumes:
      - ./logs:/app/logs
    networks:
      - genesis-ai-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # =============================================================================
  # PostgreSQL Database Dédiée
  # =============================================================================
  genesis-ai-db:
    image: postgres:15-alpine
    container_name: genesis-ai-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: genesis_ai_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: genesis_ai_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - genesis_ai_db_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - genesis-ai-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U genesis_ai_user -d genesis_ai_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # =============================================================================
  # Redis Virtual File System
  # =============================================================================
  genesis-ai-redis:
    image: redis:7-alpine
    container_name: genesis-ai-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - genesis_ai_redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - genesis-ai-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # =============================================================================
  # Monitoring Prometheus (Optionnel)
  # =============================================================================
  prometheus:
    image: prom/prometheus:latest
    container_name: genesis-ai-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - genesis-ai-network
    profiles:
      - monitoring

  # =============================================================================
  # Grafana Dashboard (Optionnel)
  # =============================================================================
  grafana:
    image: grafana/grafana:latest
    container_name: genesis-ai-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin123}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - genesis-ai-network
    profiles:
      - monitoring

# =============================================================================
# Volumes Persistants
# =============================================================================
volumes:
  genesis_ai_db_data:
    driver: local
  genesis_ai_redis_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

# =============================================================================
# Réseau Dédié
# =============================================================================
networks:
  genesis-ai-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
