"""Initial migration

Revision ID: 2c43863b5e49
Revises: 
Create Date: 2025-08-20 00:10:32.660871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c43863b5e49'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('dc360_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dc360_user_id'), 'users', ['dc360_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('businesses',
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('mission', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('differentiation', sa.Text(), nullable=True),
    sa.Column('value_proposition', sa.Text(), nullable=True),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('cultural_context', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_business_name'), 'businesses', ['business_name'], unique=False)
    op.create_index(op.f('ix_businesses_id'), 'businesses', ['id'], unique=False)
    op.create_index(op.f('ix_businesses_sector'), 'businesses', ['sector'], unique=False)
    op.create_table('coaching_sessions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('INITIALIZED', 'IN_PROGRESS', 'COACHING_COMPLETE', 'SUB_AGENTS_RUNNING', 'BRIEF_READY', 'COMPLETED', 'FAILED', name='sessionstatusenum'), nullable=True),
    sa.Column('current_step', sa.Enum('VISION', 'MISSION', 'CLIENTELE', 'DIFFERENTIATION', 'OFFRE', 'SYNTHESIS', name='coachingstepenum'), nullable=True),
    sa.Column('step_completion', sa.JSON(), nullable=True),
    sa.Column('coaching_confidence', sa.Float(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('cultural_context', sa.JSON(), nullable=True),
    sa.Column('sector_context', sa.JSON(), nullable=True),
    sa.Column('coaching_plan', sa.JSON(), nullable=True),
    sa.Column('conversation_history', sa.JSON(), nullable=True),
    sa.Column('coaching_duration', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_sessions_id'), 'coaching_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_coaching_sessions_session_id'), 'coaching_sessions', ['session_id'], unique=True)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('business_stage', sa.String(), nullable=True),
    sa.Column('preferred_language', sa.String(), nullable=True),
    sa.Column('coaching_style', sa.String(), nullable=True),
    sa.Column('cultural_context', sa.JSON(), nullable=True),
    sa.Column('business_context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_table('business_briefs',
    sa.Column('coaching_session_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('vision', sa.Text(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('differentiation', sa.Text(), nullable=False),
    sa.Column('value_proposition', sa.Text(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('location', sa.JSON(), nullable=True),
    sa.Column('market_research', sa.JSON(), nullable=True),
    sa.Column('content_generation', sa.JSON(), nullable=True),
    sa.Column('logo_creation', sa.JSON(), nullable=True),
    sa.Column('seo_optimization', sa.JSON(), nullable=True),
    sa.Column('template_selection', sa.JSON(), nullable=True),
    sa.Column('overall_confidence', sa.Float(), nullable=True),
    sa.Column('brief_completeness', sa.Float(), nullable=True),
    sa.Column('is_ready_for_website', sa.JSON(), nullable=True),
    sa.Column('dc360_website_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coaching_session_id'], ['coaching_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_briefs_id'), 'business_briefs', ['id'], unique=False)
    op.create_table('business_contexts',
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('market_size', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('opportunities', sa.JSON(), nullable=True),
    sa.Column('pricing_insights', sa.JSON(), nullable=True),
    sa.Column('logo_assets', sa.JSON(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('brand_guidelines', sa.JSON(), nullable=True),
    sa.Column('website_content', sa.JSON(), nullable=True),
    sa.Column('seo_metadata', sa.JSON(), nullable=True),
    sa.Column('marketing_content', sa.JSON(), nullable=True),
    sa.Column('selected_template', sa.String(), nullable=True),
    sa.Column('customizations', sa.JSON(), nullable=True),
    sa.Column('market_confidence', sa.Float(), nullable=True),
    sa.Column('content_quality', sa.Float(), nullable=True),
    sa.Column('brand_consistency', sa.Float(), nullable=True),
    sa.Column('dc360_integration_status', sa.String(), nullable=True),
    sa.Column('dc360_website_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_contexts_id'), 'business_contexts', ['id'], unique=False)
    op.create_table('coaching_steps',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.Enum('VISION', 'MISSION', 'CLIENTELE', 'DIFFERENTIATION', 'OFFRE', 'SYNTHESIS', name='coachingstepenum'), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('coach_message', sa.Text(), nullable=True),
    sa.Column('examples_provided', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('validation_criteria', sa.JSON(), nullable=True),
    sa.Column('step_duration', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['coaching_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coaching_steps_id'), 'coaching_steps', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coaching_steps_id'), table_name='coaching_steps')
    op.drop_table('coaching_steps')
    op.drop_index(op.f('ix_business_contexts_id'), table_name='business_contexts')
    op.drop_table('business_contexts')
    op.drop_index(op.f('ix_business_briefs_id'), table_name='business_briefs')
    op.drop_table('business_briefs')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_coaching_sessions_session_id'), table_name='coaching_sessions')
    op.drop_index(op.f('ix_coaching_sessions_id'), table_name='coaching_sessions')
    op.drop_table('coaching_sessions')
    op.drop_index(op.f('ix_businesses_sector'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_id'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_business_name'), table_name='businesses')
    op.drop_table('businesses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dc360_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
