"""add_pgvector_and_embeddings

Revision ID: ae73e9948b76
Revises: f45c116fedf1
Create Date: 2025-12-18 22:03:12.238344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'ae73e9948b76'
down_revision: Union[str, Sequence[str], None] = 'f45c116fedf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create vector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_embeddings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('embedding_type', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_embeddings_brief_id'), 'user_embeddings', ['brief_id'], unique=False)
    op.create_index(op.f('ix_user_embeddings_id'), 'user_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_user_embeddings_user_id'), 'user_embeddings', ['user_id'], unique=False)
    
    # Create HNSW index for fast vector similarity search
    op.execute('''
        CREATE INDEX ix_user_embeddings_embedding 
        ON user_embeddings 
        USING hnsw (embedding vector_cosine_ops)
    ''')

    op.drop_column('user_profiles', 'experience_level')
    op.drop_column('user_profiles', 'business_stage')
    op.drop_column('user_profiles', 'sector')
    op.execute('DROP INDEX IF EXISTS ix_user_embeddings_embedding')
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.add_column('user_profiles', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('business_stage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('experience_level', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_embeddings_user_id'), table_name='user_embeddings')
    op.drop_index(op.f('ix_user_embeddings_id'), table_name='user_embeddings')
    op.drop_index(op.f('ix_user_embeddings_brief_id'), table_name='user_embeddings')
    op.drop_table('user_embeddings')
    # ### end Alembic commands ###
