"""Update User model for standalone auth

Revision ID: d3ea4d165475
Revises: 2c43863b5e49
Create Date: 2025-08-20 01:06:31.721187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3ea4d165475'
down_revision: Union[str, Sequence[str], None] = '2c43863b5e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_index(op.f('ix_users_dc360_user_id'), table_name='users')
    op.drop_column('users', 'name')
    op.drop_column('users', 'dc360_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dc360_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_users_dc360_user_id'), 'users', ['dc360_user_id'], unique=True)
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
